[package]
name = "microtun-stm32h753zi-bootloader"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
embassy-boot-stm32 = { version = "0.8.0", default-features = false }
embassy-stm32 = { version = "0.6.0", features = ["stm32h753zi"] }
embassy-sync = { version = "0.8.0", default-features = false }
cortex-m = { version = "0.7.6", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.0"
