[package]
name = "microtun-telnet"
description = "Interactive Telnet client with YMODEM file upload support"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
clap = { version = "~4.6", features = ["derive"] }
crossterm = { version = "=0.28.1", features = ["event-stream"] }
embedded-io-adapters = { version = "0.7", features = ["tokio-1"] }
embedded-io-async = { workspace = true, features = ["std"] }
futures-util = "=0.3.31"
microtun-ymodem = { workspace = true }
ratatui = "=0.29.0"
tokio = { version = "~1.53", features = ["fs", "io-util", "macros", "net", "rt-multi-thread", "time"] }
tui-term = "=0.2.0"

[[bin]]
name = "microtun-telnet"
path = "src/main.rs"
