[package]
name = "microtun-esp32-c6"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
microtun-embassy = { workspace = true, features = ["alloc", "log"] }
microtun-net-util = { workspace = true, features = ["embassy-net"] }
microtun-mcuboot = { workspace = true }
microtun-cli = { workspace = true }
microtun-firmware-common = { workspace = true, features = ["log"] }

embassy-executor = { workspace = true, features = ["log"] }
embassy-net = { workspace = true, features = ["log", "tcp", "udp", "icmp", "dhcpv4", "dhcpv4-hostname", "dns", "medium-ethernet", "medium-ip", "proto-ipv4", "proto-ipv6", "multicast"] }
embassy-net-driver-channel = { workspace = true }
embassy-sync = { workspace = true }
embassy-time = { workspace = true, features = ["log"] }
embedded-io-async = { workspace = true }
embedded-storage = { workspace = true }
heapless = { workspace = true }
rand_core = { workspace = true }
static_cell = { workspace = true }

log = { workspace = true }

esp-alloc = { workspace = true }
esp-bootloader-esp-idf = { workspace = true, features = ["esp32c6"] }
esp-hal = { workspace = true, features = ["esp32c6", "log-04", "unstable"] }
esp-println = { workspace = true, features = ["esp32c6", "log-04"] }
esp-radio = { workspace = true, features = ["esp32c6", "log-04", "wifi"] }
esp-rtos = { workspace = true, features = ["esp32c6", "esp-radio", "esp-alloc", "embassy", "log-04"] }
esp-storage = { workspace = true, features = ["esp32c6"] }

[build-dependencies]
microtun-firmware-build = { workspace = true }
