[package]
name = "microtun-stm32h753zi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
microtun-embassy = { workspace = true, features = ["defmt"] }
microtun-mcuboot = { workspace = true, features = ["defmt"] }
microtun-net-util = { workspace = true, features = ["embassy-net"] }
microtun-cli = { workspace = true, features = ["defmt"] }
microtun-firmware-common = { workspace = true, features = ["defmt"] }

embassy-executor = { workspace = true, features = ["platform-cortex-m", "executor-thread", "defmt"] }
embassy-net = { workspace = true, features = ["defmt", "tcp", "udp", "icmp", "dhcpv4", "dhcpv4-hostname", "dns", "medium-ethernet", "medium-ip", "proto-ipv4", "proto-ipv6", "multicast"] }
embassy-net-driver-channel = { workspace = true }
embassy-boot = { version = "0.7.0", default-features = false }
embedded-io-async = { workspace = true }
embedded-storage = { workspace = true }
embassy-stm32 = { workspace = true, features = ["defmt", "stm32h753zi", "time-driver-tim2", "chrono", "unstable-pac"] }
embassy-sync = { workspace = true, features = ["defmt"] }
embassy-time = { workspace = true, features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768"] }
heapless = { workspace = true }
chrono = { version = "0.4", default-features = false }
static_cell = { workspace = true }
rand_core = { workspace = true }

defmt = { workspace = true }
defmt-rtt = "1.0.0"
cortex-m = { workspace = true }
cortex-m-rt = { workspace = true }

[build-dependencies]
microtun-firmware-build = { workspace = true }