use std::{env, fs, net::Ipv4Addr, path::PathBuf};

use base64::{Engine as _, engine::general_purpose::STANDARD};

fn main() {
    for name in [
        "MICROTUN_PRIVATE_KEY",
        "MICROTUN_API_SERVER_PUBLIC_KEY",
        "MICROTUN_API_SERVER",
        "MICROTUN_API_SERVER_TUNNEL_ADDR",
        "MICROTUN_TUNNEL_ADDR",
        "MICROTUN_NTP_SERVER",
        "MICROTUN_NTP_PORT",
    ] {
        println!("cargo:rerun-if-env-changed={name}");
    }

    let private_key = required_wireguard_key("MICROTUN_PRIVATE_KEY");
    let api_server_public_key = required_wireguard_key("MICROTUN_API_SERVER_PUBLIC_KEY");

    let api_server = required_text("MICROTUN_API_SERVER");
    let (api_server_host, api_server_port) = host_port("MICROTUN_API_SERVER", &api_server);
    let api_server_tunnel_addr = required_ipv4("MICROTUN_API_SERVER_TUNNEL_ADDR");
    let api_server_tunnel_cidr = format!("{api_server_tunnel_addr}/32");
    let local_tunnel_addr = required_text("MICROTUN_TUNNEL_ADDR");
    let (local_tunnel_ipv4, local_tunnel_prefix_len) =
        ipv4_cidr("MICROTUN_TUNNEL_ADDR", &local_tunnel_addr);
    let ntp_server = text("MICROTUN_NTP_SERVER", "time.google.com");
    let ntp_port = number::<u16>("MICROTUN_NTP_PORT", "123");

    let generated = format!(
        r#"// @generated by build.rs -- do not edit.

/// Device WireGuard private key, in standard WireGuard base64 form.
pub const PRIVATE_KEY: &str = {private_key:?};

/// Static public key of the pinned Peers API server, in WireGuard base64 form.
pub const API_SERVER_PUBLIC_KEY: &str = {api_server_public_key:?};

/// API server host and port. The host is resolved by the ESP32-C3 at runtime.
pub const API_SERVER_HOST: &str = {api_server_host:?};
pub const API_SERVER_PORT: u16 = {api_server_port};

/// Inner address routed to the pinned Peers API server. It is always a host route.
pub const API_SERVER_TUNNEL_ADDR: [u8; 4] = {api_server_tunnel_addr:?};
pub const API_SERVER_TUNNEL_CIDR: &str = {api_server_tunnel_cidr:?};
pub const PEERS_API_PORT: u16 = 80;

/// This board's address on the microtun network.
pub const LOCAL_TUNNEL_IPV4: [u8; 4] = {local_tunnel_ipv4:?};
pub const LOCAL_TUNNEL_PREFIX_LEN: u8 = {local_tunnel_prefix_len};

/// Outer UDP port used by microtun/WireGuard.
pub const LISTEN_PORT: u16 = 51820;

/// Telnet-ish shell port on the inner tunnel stack.
pub const TELNET_PORT: u16 = 23;

/// Public NTP hostname used to seed the firmware wall clock before microtun starts.
pub const NTP_SERVER: &str = {ntp_server:?};
pub const NTP_PORT: u16 = {ntp_port};

/// Local UDP port for the one-shot boot SNTP client.
pub const NTP_LOCAL_PORT: u16 = 49152;
"#,
        api_server_tunnel_addr = api_server_tunnel_addr.octets(),
        local_tunnel_ipv4 = local_tunnel_ipv4.octets(),
    );

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("Cargo sets OUT_DIR"));
    fs::write(out_dir.join("generated.rs"), generated).expect("write generated configuration");
}

fn env_value(name: &str) -> Option<String> {
    env::var(name).ok().filter(|value| !value.trim().is_empty())
}

fn text(name: &str, default: &str) -> String {
    env_value(name).unwrap_or_else(|| default.to_owned())
}

fn required_text(name: &str) -> String {
    env_value(name).unwrap_or_else(|| panic!("missing {name}; set it in Cargo's build environment"))
}

fn number<T>(name: &str, default: &str) -> T
where
    T: std::str::FromStr,
    T::Err: std::fmt::Display,
{
    let value = text(name, default);
    value
        .parse()
        .unwrap_or_else(|err| panic!("invalid {name}={value:?}: {err}"))
}

fn required_ipv4(name: &str) -> Ipv4Addr {
    let value = required_text(name);
    value
        .parse()
        .unwrap_or_else(|err| panic!("invalid {name}={value:?}: {err}"))
}

fn host_port(name: &str, value: &str) -> (String, u16) {
    assert!(
        !value.chars().any(char::is_whitespace),
        "invalid {name}={value:?}: endpoint must not contain whitespace"
    );

    let (host, port) = value
        .rsplit_once(':')
        .unwrap_or_else(|| panic!("invalid {name}={value:?}: expected host:port"));
    assert!(
        !host.is_empty() && !host.contains(':') && !host.contains('/'),
        "invalid {name}={value:?}: expected a hostname or IPv4 address followed by :port"
    );
    let port = port
        .parse::<u16>()
        .unwrap_or_else(|err| panic!("invalid {name}={value:?}: invalid port: {err}"));
    assert!(port != 0, "invalid {name}={value:?}: port must be non-zero");

    (host.to_owned(), port)
}

fn ipv4_cidr(name: &str, value: &str) -> (Ipv4Addr, u8) {
    let (address, prefix) = value
        .split_once('/')
        .unwrap_or_else(|| panic!("invalid {name}={value:?}: expected IPv4/prefix"));
    let address = address
        .parse::<Ipv4Addr>()
        .unwrap_or_else(|err| panic!("invalid {name}={value:?}: {err}"));
    let prefix = prefix
        .parse::<u8>()
        .unwrap_or_else(|err| panic!("invalid {name}={value:?}: {err}"));
    assert!(
        prefix <= 32,
        "invalid {name}={value:?}: prefix must be <= 32"
    );
    (address, prefix)
}

fn required_wireguard_key(name: &str) -> String {
    let value = env_value(name)
        .unwrap_or_else(|| panic!("missing {name}; set it in Cargo's build environment"));
    let decoded = STANDARD
        .decode(&value)
        .unwrap_or_else(|err| panic!("invalid {name}: expected WireGuard base64 key: {err}"));
    assert_eq!(
        decoded.len(),
        32,
        "invalid {name}: decoded WireGuard key must be exactly 32 bytes"
    );
    value
}
