[package]
name = "microtun-provisioning"
description = "Portable provisioning support and link addressing for microtun devices"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
base64 = { workspace = true }
microtun-core = { workspace = true }
crc = { version = "3.4", default-features = false }
thiserror = { workspace = true }
heapless = { workspace = true }
hex = { workspace = true }
embassy-net = { version = "0.9.1", default-features = false, features = [
    "udp",
    "proto-ipv4",
    "multicast",
    "medium-ethernet",
], optional = true }
static_cell = { version = "2", optional = true }
defmt = { workspace = true, optional = true }

[features]
default = ["std"]
std = []
embassy-net = ["dep:embassy-net", "dep:static_cell"]
defmt = ["dep:defmt"]

